name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  msrv:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install toolchain
      uses: actions-rs/toolchain@v1.0.3
      with:
        toolchain: 1.31.0
        profile: minimal
    - name: Install libftdi1-dev
      run: sudo apt-get install libftdi1-dev
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose

  msrv-bindgen:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install toolchain
      uses: actions-rs/toolchain@v1.0.3
      with:
        toolchain: 1.34.0
        profile: minimal
    - name: Install libftdi1-dev
      run: sudo apt-get install libftdi1-dev
    - name: Build
      run: cargo build --verbose --features=bindgen
    - name: Run tests
      run: cargo test --verbose --features=bindgen

  nightly:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install toolchain
      uses: actions-rs/toolchain@v1.0.3
      with:
        toolchain: nightly
        profile: minimal
    - name: Install libftdi1-dev
      run: sudo apt-get install libftdi1-dev
    - name: Build and run tests (pregenerated)
      run: cargo test --verbose
    - name: Build and run tests (bindgen)
      run: cargo test --verbose --features=bindgen

  windows-msvc:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install toolchain
      uses: actions-rs/toolchain@v1.0.3
      with:
        toolchain: 1.34.0
        target: x86_64-pc-windows-msvc
        profile: minimal
    - name: Restore / setup vcpkg and libftdi1
      uses: lukka/run-vcpkg@master
      with:
        vcpkgArguments: 'libftdi1:x64-windows'
        vcpkgGitCommitId: '7aebb48' # 2020.01
    - name: Build and run tests (pregenerated)
      run: cargo test --verbose
    - name: Build and run tests (bindgen)
      run: cargo test --verbose --features=bindgen
