name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  linux:
    strategy:
      matrix:
        include:
        - name: MSRV (minimal)
          toolchain: 1.31.0
          features: ""
        - name: MSRV (libusb1-sys)
          toolchain: 1.32.0
          features: libusb1-sys
        - name: MSRV (bindgen)
          toolchain: 1.34.0
          features: bindgen
        - name: Nightly
          toolchain: nightly
          features: libusb1-sys,bindgen
      fail-fast: false

    name: ${{ matrix.name }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install toolchain
      uses: actions-rs/toolchain@v1.0.3
      with:
        toolchain: ${{ matrix.toolchain }}
        profile: minimal
        default: true
    - name: Install libftdi1-dev
      run: sudo apt-get install libftdi1-dev
    - run: cargo build --verbose --features=${{ matrix.features }}
    - run: cargo test --verbose --features=${{ matrix.features }}

  windows-msvc:
    runs-on: windows-latest
    env:
      VCPKGRS_DYNAMIC: 1
    steps:
    - uses: actions/checkout@v2
    - name: Install toolchain
      uses: actions-rs/toolchain@v1.0.3
      with:
        toolchain: 1.34.0
        target: x86_64-pc-windows-msvc
        profile: minimal
        default: true
    - name: Restore / setup vcpkg and libftdi1
      uses: lukka/run-vcpkg@master
      with:
        vcpkgArguments: 'libftdi1:x64-windows'
        vcpkgGitCommitId: '7aebb48' # 2020.01
    - name: Build and run tests (pregenerated)
      run: cargo test --verbose
